import Head from "next/head";
import Image from "next/image";
import React from "react";
import styles from "../../styles/Home.module.css";
import booksIcon from "public/images/book-icon.jpeg";
import { books } from "../api/books.js";

export default function HomePage() {
  return (
    <React.Fragment>
      <Head>
        <title>Debbie&apos;s BookStore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/book-icon.jpeg" />
      </Head>  

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Debbie&apos;s BookStore</h1>
        <div style={{  textAlign: "center"}}>
          <Image
            alt="books image"
            src="/images/book-icon.jpeg"
            width="200"
            height="200"
          />
        </div>
        <h2>Choose from our collection of books:</h2>
        <div className={styles.parentDivOfJsonDivs}>
          {books?.slice(0, 4).map((book, index) => (
            <div className={styles.jsonDivs} key={index}>
              <section className={styles.books}>
                <Image
                  alt="book img"
                  src={booksIcon}
                  width="30"
                  height="30"
                  style={{ margin: ".6rem" }}></Image>
                {" "}
                <div>
                  <span style={{fontWeight: "bold"}}>Book Title: </span>
                  {book.title}
                </div>
              </section>
              <section className={styles.books}>
                <Image
                  alt="book img"
                  src={booksIcon}
                  width="30"
                  height="30"
                  style={{ margin: ".6rem" }}
                />
                <div>
                  <span style={{fontWeight: "bold"}}>Book Author: </span> {book.authors}{" "}
                </div>
              </section>
              <section className={styles.books}>
                <Image
                  alt="book img"
                  src={booksIcon}
                  width="30"
                  height="30"
                  style={{ margin: ".6rem" }}
                />
                <div>
                  <span style={{fontWeight: "bold"}}>Book Category: </span>
                  {book.categories}
                </div>
              </section>
            </div>
          ))}
        </div>
      </main>
    </React.Fragment>
  );
}
