import Head from "next/head";
import Image from "next/image";
import React from "react";
import styles from "../styles/Home.module.css";
import bookImg from "/public/images/bookicon.png";
import books from "../public/json/books.json";

export default function HomePage() {
  return (
    <React.Fragment>
      <Head>
        <title>Debbie&apos;s BookStore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/bookicon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Debbie&apos;s BookStore</h1>
        <div style={{ textAlign: "center" }}>
          <Image
            alt="books image"
            src="/images/bookicon.png"
            width="200"
            height="200"
          />
        </div>
        <h2>Choose from our collection of books:</h2>
        <div className={styles.parentDivOfJsonDivs}>
          {books?.slice(0, 4).map((book, index) => (
            //we map a div which has the same entities inside it which are a little image, the book title, book author and book category!

            <div className={styles.jsonDivs + " section"} key={index}>
              <section className={styles.books}>
                <Image
                  alt="Random Books Image"
                  src={bookImg}
                  width="30"
                  height="30"
                  style={{ margin: ".6rem" }}
                ></Image>{" "}
                <div>
                  <span style={{ fontWeight: "bold" }}>Book Title: </span>
                  {/* entity which we take from the json that's why we do the mapping here*/}
                  {book.title}
                </div>
              </section>
              <section className={styles.books}>
                <Image
                  alt="Random Books Image"
                  src={bookImg}
                  width="30"
                  height="30"
                  style={{ margin: ".6rem" }}
                />
                <div>
                  <span style={{ fontWeight: "bold" }}>Book Author: </span>{" "}
                  {/* entity which we take from the json that's why we do the mapping here*/}
                  {book.authors}{" "}
                </div>
              </section>
              <section className={styles.books}>
                <Image
                  alt="Random Books Image"
                  src={bookImg}
                  width="30"
                  height="30"
                  style={{ margin: ".6rem" }}
                />
                <div>
                  <span style={{ fontWeight: "bold" }}>Book Category: </span>
                  {/* entity which we take from the json that's why we do the mapping here*/}
                  {book.categories}
                </div>
              </section>
            </div>
          ))}
        </div>
      </main>
    </React.Fragment>
  );
}
